### ISSUE TITLE
Python libraries are out of date on install

### ISSUE THREAD

**Issue by SharmaineLim** [kirigamico/generator-kirigami-wagtail#2]
`dev-requirements.txt` and `requirements.txt` contain Python libraries that are out of date. It would be nice if Python libraries are updated prior to install or if the txt files themselves are generated with the latest libraries on running the generator.

**Comment by mixxorz** [comment]
This was fixed when we switched over to Pipenv. The generator comes with a Pipfile but not a Pipfile.lock file so it will always install the latest (compatible) versions of the libraries.
